// src/lib/supabase/client.ts
import { createBrowserClient } from "@supabase/ssr";

export function createClient() {
  return createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
  );
}

// NEXT_PUBLIC_SUPABASE_ANON_KEY = "";
// NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY = "";
// SUPABASE_URL = "";
// POSTGRES_DATABASE = "";
// POSTGRES_HOST = "";
// POSTGRES_PASSWORD = "";
// POSTGRES_PRISMA_URL = "";
// POSTGRES_URL = "";
// POSTGRES_URL_NON_POOLING = "";
// POSTGRES_USER = "";
// NEXT_PUBLIC_SUPABASE_ANON_KEY = "";
// SUPABASE_JWT_SECRET = "";
// NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY = "";
// SUPABASE_SECRET_KEY = "";
// SUPABASE_SERVICE_ROLE_KEY = "";
// SUPABASE_URL = "";

// POSTGRES_PASSWORD;
// POSTGRES_HOST;
// NEXT_PUBLIC_SUPABASE_ANON_KEY;
// POSTGRES_PRISMA_URL;
// POSTGRES_USER;
// SUPABASE_ANON_KEY;
// SUPABASE_URL;
// NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
// SUPABASE_SECRET_KEY;
// SUPABASE_PUBLISHABLE_KEY;
// NEXT_PUBLIC_SUPABASE_URL;
// SUPABASE_SERVICE_ROLE_KEY;
// POSTGRES_URL_NON_POOLING;
// POSTGRES_URL;
// POSTGRES_DATABASE;
// SUPABASE_JWT_SECRET
